/**
 * Enthaelt die Texte fuer die Anwendung.
 * Vermutlich sinnvoller die dynamisch per Server aus dem "Accept-Language" herauszulesen und dann zurueckzugeben,
 * aber erstmal statisch
 */
 define({
	'application.title':'Gebiete',
	'application.header':'Gebietsanwendung',
	'userName.prompt':'Geben Sie bitte ihren Namen ein',
	'userName.noName.confirm':'Ohne Nutzernamen kann nicht auf dem Server gespeichert werden. Nur lokal arbeiten?',
	'territories.header':'Gebiete',
	'territories.select.nothingChosen':'Bitte w\u00e4hlen',
	'territories.add.caption':'+',
	'territories.add.title':'Neues Gebiet anlegen',
	'territories.add.prompt':'Bitte Namen des neuen Gebietes eingeben',
	'territories.remove.caption':'-',
	'territories.remove.title':'Gebiet entfernen',
	'territories.remove.prompt':'Soll das Gebiet wirklich entfernt werden?',
	'street.remove.caption':'-',
	'street.remove.title':'Strasse entfernen',
	'street.remove.prompt':'Soll die Straße wirklich entfernt werden?',
	'street.add.caption':'+',
	'street.add.title':'Strasse erstellen',
	'street.add.prompt':'Bitte den Namen der neuen Stra\u00dfe eingeben',
	'house.add.caption':'+',
	'house.add.title':'Haus hinzufuegen',
	'house.add.prompt':'Bitte die Hausnummer eingeben',
	'house.remove.caption':'-',
	'house.remove.title':'Haus entfernen',
	'house.remove.prompt':'Soll das Haus wirklich entfernt werden?',
	'resident.add.caption':'+',
	'resident.add.title':'Einwohner hinzufuegen',
	'resident.add.prompt':'Bitte den Namen eingeben',
	'resident.remove.caption':'-',
	'resident.remove.title':'Einwohner entfernen',
	'resident.remove.prompt':'Soll der Einwohner wirklich entfernt werden?',
	'resident.rename.caption':'umbenennen',
	'resident.rename.title':'Einwohner umbenennen',
	'resident.rename.prompt':'Bitte neuen Namen eingeben',
	'resident.status.ni.caption':'KI',
	'resident.status.ni.title':'Kein Interesse',
	'resident.status.interest.caption':'WV',
	'resident.status.interest.title':'Wieder vorsprechen'
 });